//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlantBestellingen.WPF.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlantBestellingen.WPF.Languages.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Customers.
        /// </summary>
        public static string _Customers {
            get {
                return ResourceManager.GetString("_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dutch.
        /// </summary>
        public static string _Dutch {
            get {
                return ResourceManager.GetString("_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _English.
        /// </summary>
        public static string _English {
            get {
                return ResourceManager.GetString("_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string _File {
            get {
                return ResourceManager.GetString("_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string _Language {
            get {
                return ResourceManager.GetString("_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Management.
        /// </summary>
        public static string _Management {
            get {
                return ResourceManager.GetString("_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Products.
        /// </summary>
        public static string _Products {
            get {
                return ResourceManager.GetString("_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: .
        /// </summary>
        public static string AddressTag {
            get {
                return ResourceManager.GetString("AddressTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all the customers details!.
        /// </summary>
        public static string AllCustomersDetails {
            get {
                return ResourceManager.GetString("AllCustomersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all the product details!.
        /// </summary>
        public static string AllProductDetails {
            get {
                return ResourceManager.GetString("AllProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer address.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name: .
        /// </summary>
        public static string CustomerName_ {
            get {
                return ResourceManager.GetString("CustomerName_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer: .
        /// </summary>
        public static string CustomerTag {
            get {
                return ResourceManager.GetString("CustomerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount: .
        /// </summary>
        public static string DiscountTag {
            get {
                return ResourceManager.GetString("DiscountTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised.
        /// </summary>
        public static string ExceptionRaised {
            get {
                return ResourceManager.GetString("ExceptionRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string NameTag {
            get {
                return ResourceManager.GetString("NameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New order....
        /// </summary>
        public static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order management system.
        /// </summary>
        public static string OrderManagementSystem {
            get {
                return ResourceManager.GetString("OrderManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected order has .
        /// </summary>
        public static string OrderProductCount {
            get {
                return ResourceManager.GetString("OrderProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders: .
        /// </summary>
        public static string Orders_ {
            get {
                return ResourceManager.GetString("Orders_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid?.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid: .
        /// </summary>
        public static string PaidTag {
            get {
                return ResourceManager.GetString("PaidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the order paid?.
        /// </summary>
        public static string PaidToolTip {
            get {
                return ResourceManager.GetString("PaidToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: .
        /// </summary>
        public static string PriceTag {
            get {
                return ResourceManager.GetString("PriceTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  product(s).
        /// </summary>
        public static string ProductProducts {
            get {
                return ResourceManager.GetString("ProductProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products: .
        /// </summary>
        public static string ProductsTag {
            get {
                return ResourceManager.GetString("ProductsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the customer?.
        /// </summary>
        public static string RemoveCustomer {
            get {
                return ResourceManager.GetString("RemoveCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: remove customer.
        /// </summary>
        public static string RemoveCustomerError {
            get {
                return ResourceManager.GetString("RemoveCustomerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: remove product.
        /// </summary>
        public static string RemoveOrderError {
            get {
                return ResourceManager.GetString("RemoveOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First delete all orders from .
        /// </summary>
        public static string RemoveOrdersFromCustomer {
            get {
                return ResourceManager.GetString("RemoveOrdersFromCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First remove this product from all orders.
        /// </summary>
        public static string RemoveProductFromOrder {
            get {
                return ResourceManager.GetString("RemoveProductFromOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
    }
}
